receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # ✨ The Fix: Listen to the whole Docker network
      http:
        endpoint: "0.0.0.0:4318" # ✨ The Fix: Listen to the whole Docker network

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889"

  #otlp_grpc/traces:
  #  endpoint: "jaeger:4317" # Or jaeger:4317
  #  tls:
  #    insecure: true

  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    traces_index: "traces-otel"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, elasticsearch]
      #exporters: [debug, otlp_grpc/traces, elasticsearch]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
